blog/article/views.py
from flask import Blueprint, render_template, redirect, request, url_for
from blog.forms.article import ArticleBaseForm
from blog.forms.user import UserLoginForm
from flask_login import current_user, login_required
from blog.extenshion import db

article = Blueprint('article', __name__, static_folder='../static', url_prefix='/articles')


@article.route('/', methods=['GET'])
def article_list():
    from blog.models import Article
    articles = Article.query.all()
    return render_template('articles/list.html',
                           articles=articles)

@article.route('/<int:pk>')
def article_detail(pk: int):
    from blog.models import Article
    try:
        article = Article.query.filter_by(id=pk).options(
                db.joinedload(Article.tags)).one_or_none()
    except KeyError:
        return redirect('/articles/')
    return render_template('articles/detail.html',
                           article=article)


@article.route('/create', methods=['GET', 'POST'])
@login_required
def create_article():
    from blog.models import Tag
    error = None
    form = ArticleBaseForm(request.form)
    form.tags.choices = [(tag.id, tag.name) for tag in Tag.query.order_by('name')]
    if request.method == 'GET':

        if not current_user.is_authenticated:
            form = UserLoginForm(request.form)
            return render_template('auth/login.html', form=form)

        return render_template('articles/create.html', form=form)


    if form.validate_on_submit():
        from blog.models import Article, Author, Tag

        title = form.title.data
        text = form.text.data
        
        #author = Author.query.filter_by(user_id=current_user.id).first_or_none()

        if not current_user.author:
            author = Author(user_id=current_user.id)
            db.session.add(author)
            #db.session.flush()
            db.session.commit()
        author_id = current_user.author.id

        article = Article(title=title, text=text, author_id=author_id)
        if form.tags.data:
            selected_tags = Tag.query.filter(Tag.id.in_(form.tags.data))
            for tag in selected_tags:
                article.tags.append(tag)
        db.session.add(article)

        try:
            db.session.commit()
        except:
            error = "Could not create user!"
            return render_template('articles/create.html', form=form, error=error)
        else:
            return redirect(url_for(".article_list"))
    
@article.route('/<string:tag>', methods=['GET'])
def articles_by_tag(tag):
    from blog.models import Article, Tag
    filter_tag = Tag.query.filter(Tag.name==tag).one_or_none()
    if filter_tag:
        articles = Article.query.filter(Article.tags.contains(filter_tag))
        return render_template('articles/list.html',
                           articles=articles)
    error = f'For this tag "{tag}": articles are absent yet'
    return render_template('articles/list.html',
                           error=error)

blog/index/views.py
from flask import Blueprint, render_template, redirect

index = Blueprint('index', __name__, static_folder='../static', url_prefix='/')

@index.route('/')
def index_page():
    return render_template('index.html', endpoint='index')

blog/user/views.py
from flask import Blueprint, render_template, redirect
from flask_login import login_required
from werkzeug.exceptions import NotFound

user = Blueprint('user', __name__, static_folder='../static', url_prefix='/users')

@user.route('/')
def user_list():
    from ..models import User
    users = User.query.all()
    return render_template(
        "users/list.html",
        users=users
    )


@user.route('/<int:pk>')
@login_required
def user_detail(pk: int):
    from ..models import User
    _user = User.query.filter_by(id=pk).one_or_none()
    if _user is None:
        raise NotFound("User id:{}, not found".format(pk))
    return render_template(
        "users/detail.html",
        user=_user
    )

def get_user_name(pk: int):
    if pk in USERS:
        user_name = USERS[pk]['name']
    else:
        raise NotFound(f'User id: {pk}, not found!')
    return user_name

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %} My app - {% endblock %}</title>
    {% block css %}
    <link
      href="{{ url_for('static', filename='css/bootstrap.min.css')}}"
      rel="stylesheet"
    />
    {% endblock %}
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class="container">
      <!-- prettier-ignore -->
      {% block body %} 
      {% endblock %}
    </div>

    {% block js %}
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
    {% endblock %}
  </body>
</html>

blog/templates/index.html
{% extends 'base.html' %}

<!-- prettier-ignore -->
{% block title %} 
Main page
{% endblock %}

{% block body %}
<div class="container text-center justify-content-between">
  <h2 class="text-center">Welcome</h2>
  <div class="row justify-content-between">
    <div class="col justify-content-center">
      <div class="card" style="width: 18rem">
        <div class="card-body">
          <h5 class="card-title">Articles</h5>
          <p class="card-text">
            Some quick example text to build on the card title and make up the
            bulk of the card's content.
          </p>
          <a href="{{ url_for('article.article_list' ) }}" class="card-link"
            >Go to Articles</a
          >
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card" style="width: 18rem">
        <div class="card-body">
          <h5 class="card-title">Users</h5>
          <p class="card-text">
            Some quick example text to build on the card title and make up the
            bulk of the card's content.
          </p>
          <a href="{{ url_for('user.user_list' ) }}" class="card-link"
            >Go to Users</a
          >
        </div>
      </div>

      <!-- prettier-ignore -->
      {% endblock %}
    </div>
  </div>
</div>

blog/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('index.index_page') }}"
      >GB Flask</a
    >
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" href="{{ url_for('index.index_page') }}"
            >Home</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{{ url_for('user.user_list') }}"
            >Users</a
          >
        </li>
        <li class="nav-item">
          <a
            class="nav-link active"
            href="{{ url_for('article.article_list') }}"
            >Articles</a
          >
        </li>
        <li class="nav-item">
          <a
            class="nav-link active"
            href="{{ url_for('article.create_article') }}"
            >Create article</a
          >
        </li>
        {% if current_user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" href="{{ url_for('auth.logout') }}"
            >Logout ({{ current_user.email }})</a
          >
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link active" href="{{ url_for('auth.login') }}"
            >Login</a
          >
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>