blog/forms/article.py
from flask_wtf import FlaskForm
from wtforms import StringField, validators, TextAreaField, SubmitField, SelectMultipleField 

class ArticleBaseForm(FlaskForm):
    title = StringField('Title', [validators.DataRequired()])
    text = TextAreaField('Article text', [validators.DataRequired()])
    tags = SelectMultipleField('Tags', coerce=int)
    submit = SubmitField('Create')

blog/article/views.py
from flask import Blueprint, render_template, redirect, request, url_for
from blog.forms.article import ArticleBaseForm
from blog.forms.user import UserLoginForm
from flask_login import current_user, login_required
from blog.extenshion import db

article = Blueprint('article', __name__, static_folder='../static', url_prefix='/articles')


@article.route('/', methods=['GET'])
def article_list():
    from blog.models import Article
    articles = Article.query.all()
    return render_template('articles/list.html',
                           articles=articles)

@article.route('/<int:pk>')
def article_detail(pk: int):
    from blog.models import Article
    try:
        article = Article.query.filter_by(id=pk).options(
                db.joinedload(Article.tags)).one_or_none()
    except KeyError:
        return redirect('/articles/')
    return render_template('articles/detail.html',
                           article=article)


@article.route('/create', methods=['GET', 'POST'])
@login_required
def create_article():
    from blog.models import Tag
    error = None
    form = ArticleBaseForm(request.form)
    form.tags.choices = [(tag.id, tag.name) for tag in Tag.query.order_by('name')]
    if request.method == 'GET':

        if not current_user.is_authenticated:
            form = UserLoginForm(request.form)
            return render_template('auth/login.html', form=form)

        return render_template('articles/create.html', form=form)


    if form.validate_on_submit():
        from blog.models import Article, Author, Tag

        title = form.title.data
        text = form.text.data
        
        #author = Author.query.filter_by(user_id=current_user.id).first_or_none()

        if not current_user.author:
            author = Author(user_id=current_user.id)
            db.session.add(author)
            #db.session.flush()
            db.session.commit()
        author_id = current_user.author.id

        article = Article(title=title, text=text, author_id=author_id)
        if form.tags.data:
            selected_tags = Tag.query.filter(Tag.id.in_(form.tags.data))
            for tag in selected_tags:
                article.tags.append(tag)
        db.session.add(article)

        try:
            db.session.commit()
        except:
            error = "Could not create user!"
            return render_template('articles/create.html', form=form, error=error)
        else:
            return redirect(url_for(".article_list"))
    
@article.route('/<string:tag>', methods=['GET'])
def articles_by_tag(tag):
    from blog.models import Article, Tag
    filter_tag = Tag.query.filter(Tag.name==tag).one_or_none()
    if filter_tag:
        articles = Article.query.filter(Article.tags.contains(filter_tag))
        return render_template('articles/list.html',
                           articles=articles)
    error = f'For this tag "{tag}": articles are absent yet'
    return render_template('articles/list.html',
                           error=error)

blog/user/views.py
from flask import Blueprint, render_template, redirect
from flask_login import login_required
from werkzeug.exceptions import NotFound

user = Blueprint('user', __name__, static_folder='../static', url_prefix='/users')

@user.route('/')
def user_list():
    from ..models import User
    users = User.query.all()
    return render_template(
        "users/list.html",
        users=users
    )


@user.route('/<int:pk>')
@login_required
def user_detail(pk: int):
    from ..models import User
    _user = User.query.filter_by(id=pk).one_or_none()
    if _user is None:
        raise NotFound("User id:{}, not found".format(pk))
    return render_template(
        "users/detail.html",
        user=_user
    )

def get_user_name(pk: int):
    if pk in USERS:
        user_name = USERS[pk]['name']
    else:
        raise NotFound(f'User id: {pk}, not found!')
    return user_name

blog/templates/articles/create.html
<!-- prettier-ignore -->
{% extends "base.html" %} 
{% from "macro/formhelpers.html" import render_field %}
{% block title %} Create new article {% endblock %} 
{% block body %}
<h1>Create article</h1>
<!-- prettier-ignore -->
{% with messages = get_flashed_messages() %}
{% if error %}
<div class="alert alert-danger" role="alert">{{ error }}</div>
{% endif %}
<!-- prettier-ignore -->
{% endwith %}

<form method="post">
  <!-- prettier-ignore -->
  {{ form.csrf_token }}
  {% for field in ['title', 'text', 'tags'] %}
  {{ render_field(form[field]) }}
  {% endfor %}
  <div>{{ form.submit(class="btn btn-primary mb-3") }}</div>
</form>
{% endblock %}

blog/templates/articles/detail.html
{% extends 'base.html' %}

<!-- prettier-ignore -->
{% block title %} 
{{ super() }}
Article detail 
{% endblock %}

{% block body %}
<h2 class="text-center">Article detail</h2>
<div class="card">
  <img src="..." class="card-img-top" alt="" />

  <div class="card-body">
    <h5 class="card-title">{{ article.title }}</h5>
    <p class="card-text">{{ article.text }}</p>
    <a
      href="{{ url_for('user.user_detail', pk=article.author.user_id ) }}"
      class="btn btn-primary"
      >Author: {{ article.author.user.first_name }} {{
      article.author.user.last_name }}</a
    >
    <!-- prettier-ignore -->
    {% if article.tags %}
    <div>Tags:</div>
    <ul>
      {% for tag in article.tags %}
      <a href="{{ url_for('article.articles_by_tag', tag=tag.name ) }}"
        ><span class="badge text-bg-dark">{{ tag.name }}</span></a
      >
      {% endfor %}
    </ul>
    {% endif %}
  </div>
</div>

<!-- prettier-ignore -->
{% endblock %}

blog/templates/articles/list.html
{% extends 'base.html' %}

<!-- prettier-ignore -->
{% block title %} 
{{ super() }}
Article list 
{% endblock %}
<!-- prettier-ignore -->
{% block body %}
<div class="container text-center">
  <div class="row">
    {% if error %}
    <div class="alert alert-danger" role="alert">{{ error }}</div>
    {% endif %}
    <h1>Articles</h1>
    {% for article in articles %}
    <div class="col">
      <div class="card" style="width: 18rem">
        <img src="..." class="card-img-top" alt="..." />
        <div class="card-body">
          <h5 class="card-title">{{ article.title }}</h5>
          <p class="card-text">{{ article.text }}</p>
          <a
            href="{{ url_for('article.article_detail', pk=article.id) }}"
            class="btn btn-primary"
            >Learn more...</a
          >
        </div>
      </div>

      <!-- prettier-ignore -->
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}