blog/author/views.py
from flask import Blueprint, render_template, redirect
from flask_login import login_required
from werkzeug.exceptions import NotFound

author = Blueprint('author', __name__, static_folder='../static', url_prefix='/authors')

@author.route('/')
def author_list():
    from ..models import Author
    authors = Author.query.all()
    return render_template(
        "authors/list.html",
        authors=authors
    )


@author.route('/<int:pk>')
@login_required
def author_detail(pk: int):
    from ..models import Author
    _author = Author.query.filter_by(id=pk).one_or_none()
    if _author is None:
        raise NotFound("Author id:{}, not found".format(pk))
    return render_template(
        "authors/detail.html",
        author=_author
    )

def get_user_name(pk: int):
    if pk in USERS:
        user_name = USERS[pk]['name']
    else:
        raise NotFound(f'User id: {pk}, not found!')
    return user_name

blog/templates/authors/detail.html
{% extends 'base.html' %}

<!-- prettier-ignore -->
{% block title %} 
Author detail 
{% endblock %}

{% block body %}
<h1>
  {{ author.user.first_name }} {{ author.user.last_name }} ({{ author.user.email
  }})
</h1>
{% endblock %}

blog/templates/authors/list.html
{% extends 'base.html' %}

<!-- prettier-ignore -->
{% block title %} 
Authors list 
{% endblock %}

{% block body %}
<div class="container">
  <h1 class="text-center">Authors</h1>
  {% for author in authors %}
  <div class="row">
    <div class="col">
      <a
        href="{{ url_for('author.author_detail', pk=author.id) }}"
        class="btn btn-outline-secondary mb-3"
        role="button"
        >{{ author.user.email }}</a
      >

      <!-- prettier-ignore -->
      {% endfor %}
    </div>

    {% endblock %}
  </div>
</div>